CREATE TABLE category (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL); 
CREATE TABLE product (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, price DECIMAL(12, 2)); 
ALTER TABLE product ADD COLUMN categoryId INT DEFAULT NULL;
ALTER TABLE product ADD COLUMN description VARCHAR(255) DEFAULT NULL;
ALTER TABLE product ADD COLUMN img VARCHAR(255) DEFAULT NULL;
ALTER TABLE product ADD COLUMN size VARCHAR(255) DEFAULT NULL;
ALTER TABLE product ADD COLUMN availability VARCHAR(50) DEFAULT 'Есть';
CREATE TABLE orders (id INT AUTO_INCREMENT PRIMARY KEY, address VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, productId INT NOT NULL, price DECIMAL(12, 2));
ALTER TABLE orders ADD COLUMN createdAt DATETIME DEFAULT NULL;
update orders set createdAt = NOW() where createdAt is NULL;

-- Таблица для избранных товаров
CREATE TABLE favorites (id INT AUTO_INCREMENT PRIMARY KEY, productId INT NOT NULL, sessionId VARCHAR(255) NOT NULL, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE favorites ADD FOREIGN KEY (productId) REFERENCES product(id) ON DELETE CASCADE;
